FROM python:3.12-slim

RUN mkdir -p 'C:/latex/im_21'

# Install your script deps here
RUN pip install --no-cache-dir pillow

# Add more if needed:
# RUN pip install --no-cache-dir pillow numpy requests ...

ENTRYPOINT ["python"]
