spring:
  application:
    name: Reshavalnik
  data:
    mongodb:
      uri: ${MONGO_URL}

server:
  port: 8080

python:
  bin: python3

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

sentry:
  dsn: ${SENTRY_DNS}
  traces-sample-rate: 1.0

jwt:
  secret:
    key: reshavalnikreshavalnikreshavalnikreshavalnikreshavalnikreshavalnikreshavalnikreshavalnikreshavalnikreshavalnik
    jwtExpirationMs: 155520000000
  cookie:
    name: JWT
    sameSite: None
    secure: true

temp:
  file:
    path: ./app/temp-cache
